apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-100m 
spec:
  capacity:
    storage: 100M # 定义存储大小
  accessModes:
    - ReadWriteMany # 访问模式
  nfs:
    server: k8s-worker1
    path: /nfs/shared

