apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-deployment-pod-manager-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: my-sa
  namespace: default   # my-sa的命名空间
roleRef:
  kind: ClusterRole
  name: deployment-pod-manager
  apiGroup: rbac.authorization.k8s.io

